####### APPLICATION MONITORING ################
info.app.name=Eds SRV Log Ingestion
info.app.description=Eds SRV Log Ingestor for FSE
info.app.version=1.0.0

#######################################
#  KAFKA 
#######################################
kafka.bootstrap-servers=localhost:29092
kafka.consumer.bootstrap-servers=localhost:29092
spring.sleuth.messaging.kafka.enabled=false
kafka.properties.security.protocol=PLAINTEXT
kafka.properties.sasl.mechanism=PLAINTEXT
kafka.properties.sasl.jaas.config=PLAINTEXT
kafka.properties.ssl.truststore.location=PLAINTEXT
kafka.properties.ssl.truststore.password=PLAINTEXT
kafka.enablessl=false

#######################################
#	Database
#######################################
spring.data.mongodb.uri=mongodb://localhost:27888
spring.data.mongodb.database=FSE_EDS

####### LOGGING OUTPUT FORMAT ############
# Must be one of console, json
#######################################
log.output.format=console

########OPENTELEMETRY################################
otel.traces.exporter=logging
otel.logs.exporter=none
otel.metrics.exporter=none
 
otel.propagators=tracecontext,baggage